### PR TITLE
Notes lookup.

### LINKED ISSUE #7: How to view contents of a book?

### PR DESCRIPTION
**Pull request by michielboekhoff**
Hi there, 

This PR adds support for looking up notes in the current book and for any arbitrary book. This fixes #7 and #1. Let me know if I need to change anything.

### CODE REVIEW

**Comment by sungwoncho** [comment]
I think we can have a single interface `dnote notes` that does both features you have implemented.

How do you feel about https://github.com/dnote-io/cli/issues/10, specifically section `dnote notes`?

**Comment by michielboekhoff** [comment]
@sungwoncho Sounds good. I can change my code to work with that then.

**Comment by michielboekhoff** [comment]
I've made the proposed changes, and everything seems to be working now. 

As the complexity of the command-line increases, it might be worth the effort to look into a program that can handle command-line arguments, rather than having to manually parse these things, as flags tend to get quite tedious. At first glance, something like [Kingpin](https://github.com/alecthomas/kingpin) should work.

**Comment by sungwoncho** [comment]
Looks good to me. Thanks for the change and the suggestion.

**Pull request merged**
